### ISSUE TITLE
Latest Issue!

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe-node#14]
I updated the server then tried running and got 
```
herohamp:newawe-node MyDir$ node server.js
/Users/MyDirDocuments/Github/newawe-node/server.js:52
function substitute = function(string, data) { // Replaces string 'test{{ abc }}' with data '{"abc": "123"}' in order to make test123
                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
herohamp:newawe-node MyDir$ 
```

**Comment by Icelys** [comment]
My fault; copy and paste issue. Will fix.

**Comment by Icelys** [comment]
Ok. Fixed.
